# Generated by Django 4.1.5 on 2023-05-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
